# Default values for webgo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nwillc/webgo
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "webgo"
  vault.hashicorp.com/agent-inject-secret-database-config.json: "webgo/data/database/config"
  vault.hashicorp.com/agent-inject-template-database-config.json: |
    {{- with secret "webgo/data/database/config" -}}
    { "username": "{{ .Data.data.username }}", "password": "{{ .Data.data.password }}" }
    {{- end -}}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8888

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  foo: bar
  favorite: chocolate
