apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: gobyexample
spec:
  hosts:
  - gobyexample.com
  exportTo:
  - "."
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: wikipedia
spec:
  hosts:
    - www.wikipedia.org
  exportTo:
    - "."
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
    - www.google.com
  exportTo:
    - "."
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
