apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: gobyexample
spec:
  hosts:
  - gobyexample.com
  exportTo:
  - "."
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
